language: java

addons:
  sonarcloud:
    organization: "gestiontareas"
    token:
      secure: "oRDwNiN2jRg4f33cAVTLU9SXQmFDoLgSSbvUI9zsAg7HzBP1p+8i/IdEfwXqa5JTNtIQNYBjEt7Hz3PZcpNqeTGjeMOT3nClKauJKcSewTfETV0ynm6wzPNNWRAsvqF0thKC9OIVhByhK+dDCMFhsqG+WtMd86nDL8DcJyBH+HOgZize6TAyy1u83VbPEfSPabgfA7bJdvUsSVbuw7F+wJGdhXWi1tVnK3CzEBIBQ8E8SifQzpjkeKHw4r9N9Do2fP//oY4OLOrbKsrZzepmFInKlyDz9BCuX8P1VHuKbyC3P1uqw3xc3h3ewRlWcIr0VLx8+uI7aFPWxLajqVLkZBnbcEOp95PGNUFwmyqy1ca0vRt9BFWx+ox8USYDLBePNEjVfJc4ekIAsE2JVfUzR6hXDG/rL4hCVIyNY28x0MQYcJ6apt9pK8A8e0Oa94CpjKBPE9CjF7KK2dD8Lh4mgACqVRRQrNVkbUBjZE7XOnEf09Elz9/y0c7kVkzfDooklD/yqRjkAKoYVIgz+p8vbBpGx85po/fiVf60AG50TZvSs7G/BeyuomSG8BL5qfXinY0SSlTOLtlrk5mIz50aOACfndk+3BD11lLUBno69LQjB31G9wcKbHIm4JQPm8FKsVsSIeVw2fpfg3NRKDMZWm1a3v3IhkoTN8qzuYaVfpQ="

install:
  - npm install

script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=Aharon1377_SIGET-Grupo-2 -Dsonar.organization=gestiontareas
- mvn test

deploy: &heroku
        provider: heroku
        app: siget--equipo2
        api_key: 18562f60-1231-4327-8b42-88518f1e5dde

server:
        port: $PORT

before_install:
  - chmod +x mvnw
