language: java

addons:
  sonarcloud:
    organization: "gestiontareas"
    token: "8cc97cc1d73a3f114e96c55e4ea92056edf725d6"

install:
  - npm install

script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=Aharon1377_SIGET-Grupo-2 -Dsonar.organization=gestiontareas
- mvn test

deploy: &heroku
        skip_cleanup: true
        provider: heroku
        app: siget-equipo2
        api_key: 18562f60-1231-4327-8b42-88518f1e5dde
        on:
          branch: mantenimiento

server:
        port: $PORT

before_install:
  - chmod +x mvnw
